### ISSUE TITLE
Sample rosbag

### ISSUE THREAD

**Issue by Pokealimit** [MapIV/eagleye#100]
Hi, I would like to try out the package with the sample rosbags.
However, the provided dropbox links in the README doesn't work anymore.

**Comment by rsasaki0109** [comment]
I am sorry. We just got the link to work.

**Comment by rsasaki0109** [comment]
Here is the link.

20200127 https://www.dropbox.com/s/pfs307qn7gfeou5/eagleye_sample_20200127.bag?dl=0
20200715 https://www.dropbox.com/s/w9ag6gs17bi80st/eagleye_sample_20200715.bag?dl=0

**Comment by Pokealimit** [comment]
Thanks, can confirm both the links are working.
