### ISSUE TITLE
Canless eagleye

### ISSUE THREAD

**Issue by laitathei** [MapIV/eagleye#151]
Is eagleye_rt_canless.launch means that the package now are supporting only using GNSS and IMU data to estimate the position without out twist_topic?

**Comment by rsasaki0109** [comment]
@laitathei 
Yes, it is.
Note that canless mode may be less accurate than normal mode in non-open sky environments.

**Comment by laitathei** [comment]
Thank you. Also, I want to know that do you used any NTRIP Client service to provide RTK position or any other methods in your demo video? Because I got the same module Ublox ZED-F9P and I want to get the same result as your demo video GNSS green line.

**Comment by rsasaki0109** [comment]
@laitathei 
The eagleye demo video does not use RTK, but this is a video with twist_topic.
In the case of canless-mode, RTK must be used.

**Comment by rsasaki0109** [comment]
The issue in the title has been resolved, so I'm closing this issue.
If you have problems using canless, please open a new issue.
