### ISSUE TITLE
wrong heading/estimated_velocity_threshold in eagleye_pp_config.yaml

### ISSUE THREAD

**Issue by kazumasakawata** [MapIV/eagleye#154]
I think the parameter for estimated_velocity_threshold in eagleye_pp_config.yaml should be 2.78, not 0.278.

**Comment by rsasaki0109** [comment]
Thank you.
I've fixed it.
https://github.com/MapIV/eagleye/commit/d26eb11717c7b6637aba396e93da607c976194c8
