### ISSUE TITLE
Bag not work for ros2  

### ISSUE THREAD

**Issue by cshang412** [MapIV/eagleye#159]
when using `ros2 bag play -s rosbag_v2 eagleye_sample.bag` play bag , the **rosbag_v2** only support default msgs that  included in ros1 and ros2 standard msg, the  **rtklib_msgs/RtklibNav** msg will be  ignored.

1.  is there a way to not using  **rtklib_msgs/RtklibNav** msg ,just using **sensor_msgs/NavSatFix**  to replace gnss source as input ?

**Comment by rsasaki0109** [comment]
To play rosbag in ros1 with custom messages in ros2, please see below.
https://github.com/ros2/rosbag2_bag_v2

[rtklib_msgs/RtklibNav](https://github.com/MapIV/rtklib_ros_bridge) contains GNSS Doppler velocity (velocity in ECEF coordinate system) used in eagleye and [sensor_msgs/NavSatFix](http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/NavSatFix.html) is not a replacement.

I would like to provide sample data from ROS2 sometime in the future.

**Comment by cshang412** [comment]
thanks very much for your quick response, May i ask one more question, Since the  GNSS Dopper velocity is not common used in normal gnss device, i can only get GPRMC or GNRMC sentence which is presice position after differentiation positioning, and also i can get chassis can frame and imu frame , i want use GPRMC or GNRMC to replace the RTK input , in NMEA mode, what the difference between `/nmea_sentence_topic` and `gga_topic` ？ and both of them should have input at same time ? i that neccessary ?

**Comment by rsasaki0109** [comment]
gga_topic in yaml has disappeared in the develop branch.
So, please disregard this matter. 
https://github.com/MapIV/eagleye/blob/develop-ros1/eagleye_rt/config/eagleye_config.yaml#L8-L12

If you do not use Doppler velocity, set use_gnss_mode from RTKLIB to NMEA and specify nmea_sentence_topic including gga and rmc.

By the way, ealgeye internally converts nmea_sentence_topic(nmea_msgs/Sentence) to nmea_msgs/Gpgga and nmea_msgs/Gprmc.

**Comment by rsasaki0109** [comment]
I forgot to mention that the following package developed by map4 also provides ros1/ros2 conversion for rosbag.

https://gitlab.com/MapIV/rosbags

**Comment by rsasaki0109** [comment]
Because it has not had recent activity, I am closing this issue for now. Please comment again if you have any further issues.

**Comment by rsasaki0109** [comment]
New sample data is here.
https://drive.google.com/drive/folders/1TEaVRn7F6t8PhEfZe59gE_C1B8jZUkJo

**Comment by enescingoz** [comment]
> New sample data is here. https://drive.google.com/drive/folders/1TEaVRn7F6t8PhEfZe59gE_C1B8jZUkJo

Is there any pcd and osm data to test this dataset using Autoware?
