### ISSUE TITLE
How long does IMU only solution can stand

### ISSUE THREAD

**Issue by ajay1606** [MapIV/eagleye#228]
Hello,

Thank you so much for very impressive work and haring source.

After going through, i just curious to know, how long does localization node stable using only imu odometry ? when there is no GPS and No NDT output.

Existing autoware Localization module needs position input either from GPS or NDT, failing of both (Ex: Inside long straight Tunnel, nieghter GPS, nor NDT works)  would result in immediate failure of entire localization module.

Alternatively, if IMU only can handle for at least shorter period of time would be more beneficial in order to perform vehicle emergency maneuvers. 

Appreciate your response !

Regards,
Ajay

**Comment by rsasaki0109** [comment]
Without GNSS, eagleye performs dead reckoning with vehicle speed and IMU and its performance is 50cm error at 100m.
Automatic driving  with GNSS/IMU localization in areas without much GNSS is not recommended without LiDAR or Visual assistance.

**Comment by ajay1606** [comment]
@rsasaki0109 Thank you for your quick response.
