### ISSUE TITLE
ROS Packages uses wrong path for installation

### ISSUE THREAD

**Issue by leochien1110** [MapIV/eagleye#281]
Hi,

I would like to confirm that the path of `gsigeo2011_ver2_1.asc`. 

I followed step but there is not such file in the path `eagleye/eagleye_util/llh_converter/data/gsigeo2011_ver2_1.asc`. It turns out the file is under `llh_converter/data/gsigeo2011_ver2_1.asc`. 

Therefore, the line should be:
```bash
sudo cp llh_converter/data/gsigeo2011_ver2_1.asc /usr/share/GSIGEO/
```

This issue also appears in `main-ros1` branch. I know it is going to reach EOF but this fix will be useful for beginners. I have update the step in my [fork](https://github.com/leochien1110/eagleye) in `main-ros2` branch but not sure if it is correct. Please let me know if I should create a PR.

Thank you for all these efforts :slightly_smiling_face:

**Comment by rsasaki0109** [comment]
@leochien1110 
You are correct. Thank you for pointing out the error in the file path. Please go ahead and create a pull request to main branch.

**Comment by leochien1110** [comment]
@rsasaki0109  Just create a PR, please check.
Another issue is that this problem also happens in other branches. Though it is just a tiny fix, that will result in many PRs. Should I let your team do the rest?

**Comment by rsasaki0109** [comment]
For now, the main branch is sufficient. We will do the rest.

**Comment by rsasaki0109** [comment]
I have also fixed ROS1 and will close this issue.
https://github.com/MapIV/eagleye/commit/abf0647e6a36be78db8242ae14399616a3064630
