### ISSUE TITLE
Eagleye is not woring when use_can_less_mode is false

### ISSUE THREAD

**Issue by meliketanrikulu** [MapIV/eagleye#292]
I tested with default test data and default parameter. Just I set use_can_less_mode parameter as false. It not give an output in /eagleye/fix topic. Here is the eagleye terminal output. Can I use eagleye without vehicle twist msg. How can I fix this issue

![eagleye_canless](https://github.com/MapIV/eagleye/assets/41450930/72af0206-4f8a-4f49-bf67-b14a0a312d89)

**Comment by rsasaki0109** [comment]
Sorry, the CanLess can only operate with the following data. We will eventually turn this data into a sample rosbag.
https://drive.google.com/drive/folders/1TEaVRn7F6t8PhEfZe59gE_C1B8jZUkJo

**Comment by meliketanrikulu** [comment]
> Sorry, the CanLess can only operate with the following data. We will eventually turn this data into a sample rosbag. https://drive.google.com/drive/folders/1TEaVRn7F6t8PhEfZe59gE_C1B8jZUkJo

I cant understand why its depends on test data. What is the difference between this data and sample data in the README.md

**Comment by rsasaki0109** [comment]
sample rosbag is a rosbag with a special navsatfix that says No RTK-FIX when status is -1 and RTK FIX when status is 0. It does not support the current eagleye canless mode.
If you convert the navsatfix to nmea_msgs/Gpgga, you can run it in sample rosbag.

**Comment by meliketanrikulu** [comment]
Okey thank you for information. @rsasaki0109  Maybe you can add this on README.md file.
