### ISSUE TITLE
raw gnss data and eagleye output look mirrored to each other

### ISSUE THREAD

**Issue by meliketanrikulu** [MapIV/eagleye#293]
I visualize raw gnss data and eagleye's output (navsatfix msgs ) as local cartesian UTM. For your sample rosbag data output is as we wait . Sample data output is here:
![eagleye_default_test](https://github.com/MapIV/eagleye/assets/41450930/651e49f5-7729-4ba7-9e06-8d162c30e0ac)
The red one is raw gnss data output and blue one is eagleye output (/eagleye/fix) pose.

But I have interesting problem when i tested with my data. The poses looks mirrored. Here is the results:
![eagleye_mirror_error_3](https://github.com/MapIV/eagleye/assets/41450930/65952dfe-fc18-4d3b-bd4b-0debf08fd8cf)

My calibration is correct . I am using default parameters .

**Comment by rsasaki0109** [comment]
Does setting [`reverse_imu_wz`](https://github.com/MapIV/eagleye/blob/main-ros2/eagleye_rt/config/eagleye_config.yaml#L34) to true not solve the problem?

issue
https://github.com/MapIV/eagleye/issues/289

**Comment by meliketanrikulu** [comment]
> Does setting [`reverse_imu_wz`](https://github.com/MapIV/eagleye/blob/main-ros2/eagleye_rt/config/eagleye_config.yaml#L34) to true not solve the problem?
> 
> issue #289

Yes I tested when [reverse_imu_wz](https://github.com/MapIV/eagleye/blob/main-ros2/eagleye_rt/config/eagleye_config.yaml#L34)  is false. It gives same output

**Comment by rsasaki0109** [comment]
Is the coordinate system for the input GNSS velocity enu or ecef?
Eagleye requires gnss speed input in the ecef system in accordance with the following.
![image](https://github.com/MapIV/eagleye/assets/18298605/943d49ba-0994-45a7-99a7-2bed3a94004c)
https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-architecture/localization/

The following functions can be used to convert from enu-based velocities to ecef-based velocities.
https://github.com/MapIV/eagleye/blob/main-ros2/eagleye_core/coordinate/src/enu2xyz_vel.cpp

**Comment by rsasaki0109** [comment]
> Yes I tested when [reverse_imu_wz](https://github.com/MapIV/eagleye/blob/main-ros2/eagleye_rt/config/eagleye_config.yaml#L34) is false. It gives same output

I think the trajectories will be different depending on whether reverse_imu_wz is set to true or false. Your comment implies that both trajectories deviate from the output of GNSS data, is that correct?

**Comment by rsasaki0109** [comment]
I would like to be provided with rosbag if the above issues seem to be ok.

**Comment by meliketanrikulu** [comment]
> > Yes I tested when [reverse_imu_wz](https://github.com/MapIV/eagleye/blob/main-ros2/eagleye_rt/config/eagleye_config.yaml#L34) is false. It gives same output
> 
> I think the trajectories will be different depending on whether reverse_imu_wz is set to true or false. Your comment implies that both trajectories deviate from the output of GNSS data, is that correct?

I tested both of the [reverse_imu_wz](https://github.com/MapIV/eagleye/blob/main-ros2/eagleye_rt/config/eagleye_config.yaml#L34) settings. I set true and false . It give same output

**Comment by meliketanrikulu** [comment]
> I would like to be provided with rosbag if the above issues seem to be ok.
Okey Thank you. I will provide a rosbag .

**Comment by meliketanrikulu** [comment]
> The following functions can be used to convert from enu-based velocities to ecef-based velocities.

Thank you. Our velocities are not in the ECEF coordinates. It might be my problems reason. I will share bag file after I convert my velocities to ECEF and test with that.

**Comment by meliketanrikulu** [comment]
Hello @rsasaki0109 . Its solved when we give ECEF velocity. Thank you for your support .
