### ISSUE TITLE
Bad performance on example bag in ros2

### ISSUE THREAD

**Issue by yenlunliao** [MapIV/eagleye#317]
Hello,
I am working on the eagleye on ros2 branch.
I plot the result by Foxglove, but found the localization is not stable.

The result was showed as follow, 
Purple: localization from gnss
Blue: localization from eagleye
<img width="862" alt="Screenshot 2023-12-07 at 9 25 54 AM" src="https://github.com/MapIV/eagleye/assets/139188496/fd3e2ca4-2099-4586-8e10-fd84deddd7cf">

The localization is matched perfect initially but having the jump somewhere and misdirection after few seconds.
Any Suggestion or idea to fix it, 
Thanks.

Environment: Ubuntu 20.04/foxy, Ubuntu 20.04/humble
Config: eagleye_config.yaml in main-ros2 branch
Launch: eagleye_rt.launch.xml in main-ros2 branch
Bag: ros2 in https://drive.google.com/drive/folders/1TEaVRn7F6t8PhEfZe59gE_C1B8jZUkJo

**Comment by rsasaki0109** [comment]
Sorry, the sample IMU has a pitch of 180 degrees, so please correct the tf.
https://github.com/MapIV/eagleye/blob/main-ros2/eagleye_util/tf/launch/tf.launch.xml#L11

**Comment by yenlunliao** [comment]
I change the transform of this bag to 
```
<push-ros-namespace namespace="imu"/>
        <node name="static_transform_publisher" pkg="tf2_ros" exec="static_transform_publisher" args="0 0 0 0 3.14159265 0 base_link imu">
        </node>
```

and it performs well, thanks.
