### ISSUE TITLE
ROS2 Bag

### ISSUE THREAD

**Issue by ReginaldOlsson** [MapIV/eagleye#319]
Hello everyone. I want to try eagleye on ROS2 bag, but somehow cannot find ros2 bag(download link) to follow instructions. Can anyone please guide me where is the link for ROS2 bag file.
Thank you.

**Comment by rsasaki0109** [comment]
Please refer to this issue
https://github.com/MapIV/eagleye/issues/301

Sorry, I will update the README eventually…

**Comment by ReginaldOlsson** [comment]
Thank you
