### ISSUE TITLE
eagleye autoware

### ISSUE THREAD

**Issue by ReginaldOlsson** [MapIV/eagleye#320]
Hi again!
Can I run eagleye with autoware, simulation running in awsim?
awsim does not provide NavSatFix msg on gnss, it only provides pose without orientation.
Thank you.

**Comment by rsasaki0109** [comment]
Unfortunately, Eagleye cannot be used because there are no necessary topics in awsim.

**Comment by ReginaldOlsson** [comment]
Got it, Thank you.
