### ISSUE TITLE
Could the code work only based on GNSS and IMU?

### ISSUE THREAD

**Issue by weisongwen** [MapIV/eagleye#57]
Thanks for sharing such a good package. Could it work when the velocity information is not available from the CAN?

Best,
Weisong,

**Comment by kitsukawa** [comment]
@weisongwen At this point, velocity information from the vehicle CAN is mandatory. CAN-less Eagleye is also under development, so please wait for future updates for a while.

**Comment by weisongwen** [comment]
hi @kitsukawa , Thanks for your update! I will keep an eye on this continuously. :-)

Best,
Weisong,

**Comment by weisongwen** [comment]
Hi @kitsukawa , does the current package still requires the vehicle CAN for fusion? Since the CAN data is not usually available.

Best,
Weisong,

**Comment by weisongwen** [comment]
Dear @rsasaki0109  Thanks for your update :-)

**Comment by rsasaki0109** [comment]
We developed eagleye to work with only gnss and imu.

PR
https://github.com/MapIV/eagleye/pull/138
https://github.com/MapIV/eagleye/pull/156
