### ISSUE TITLE
Neccessary topics for bag file 

### ISSUE THREAD

**Issue by abdullahenesdoruk** [MapIV/eagleye#79]
Hi, i want to run with rosbag file. eagle_topic.yaml include  rtklib_nav_topic: /rtklib_nav
 navsatfix_topic: /f9p/fix nmea_sentence_topic: /f9p/nmea_sentence topics. Are these topics neccessary for bag file, and what topics neccessary for bag file.

**Comment by abdullahenesdoruk** [comment]
Hi, what is the meaning ecef_pos and ecef_vel in rtklib_nav ropic?

**Comment by rsasaki0109** [comment]
position and velocity in Earth-Centered` Earth-Fixed coordinate system
