### ISSUE TITLE
eagle_rt output

### ISSUE THREAD

**Issue by abdullahenesdoruk** [MapIV/eagleye#85]
Hi, i run eagle_rt launch file with eagle_sample bag file. When I start launch file, i wait 100 seconds then some status true but others false. Is that normally?
![image](https://user-images.githubusercontent.com/92039274/140638315-dbd19cce-9614-4255-a076-9f72216710e4.png)

**Comment by rsasaki0109** [comment]
That's normal.

The slip angle correction is only performed when manual_coefficient is greater than 0.
https://github.com/MapIV/eagleye/blob/master/eagleye_rt/config/eagleye_config.yaml#L57

The pitching and height functions are executed when the status of the incoming navsatfix or nmea_sentence is RTK.

**Comment by abdullahenesdoruk** [comment]
Thanks for answer.
