### ISSUE TITLE
rtkrcv server start error 

### ISSUE THREAD

**Issue by IvanGerov** [MapIV/eagleye#91]
I am getting an error related to the inpstr1-path. When I run the node, the first thing that I get is rtkrcv server start error where it cannot find the receiver. 

Solutions that I've tried:

- renamed inpstr1-path to match ttyACM0 and ttyUSB0, still the same error
- tried the sample inpstr1-path by MapIV and only changed the baud rate, still the same error

I am assuming I have to input the serial number of the chip somewhere in the config file? At least that's what I understood from the instructions. Any suggestions are highly valued, thank you!

**Comment by NikolayDonchevski** [comment]
I have the same error.

**Comment by rsasaki0109** [comment]
You may not have access to the serial port.
Please use chmod or "sudo usermod -G dialout -a $USER" to get access to the serial port.

**Comment by NikolayDonchevski** [comment]
Thank you very much for your suggestion. I tried that and I still get the same error:
"rtk server start error (str1 open error path=/serial/by-id/usb-u-blox_AG_-_www.u-blox.com_u-blox_GNSS_receiver-if00:115200:8:n:1:off)"

when I run the command: "sudo setserial /dev/ttyACM0"

I get the following message which I think is a problem:
"/dev/ttyACM0, UART: unknown, Port: 0x0000, IRQ: 0"

Is there any sort of drivers I need to install?
I am using U blox ZED-F9P on Ubuntu 18.04 with ROS melodic

**Comment by rsasaki0109** [comment]
Sorry to say this now, but you may want to reboot your PC.

**Comment by rsasaki0109** [comment]
This issue is closed for now. If you have problems again, please reopen this issue.
